// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherForecast.Infrastructure;

#nullable disable

namespace WeatherForecast.Api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231007190745_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherForecast.Domain.Aggregates.Account.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EmailAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PasswordAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PhoneNumberAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WeatherForecast.Domain.Aggregates.ForecastWeather.ForecastWeather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AtmospherePressure")
                        .HasColumnType("integer");

                    b.Property<int>("CloudBaseInMeters")
                        .HasColumnType("integer");

                    b.Property<double>("CloudinessInPercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateWeatherEvent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DewPoint")
                        .HasColumnType("double precision");

                    b.Property<int>("HorizontalVisibilityInKilometer")
                        .HasColumnType("integer");

                    b.Property<double>("HumidityInPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeatherEvent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WindId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WindId");

                    b.ToTable("ForecastsWeather");
                });

            modelBuilder.Entity("WeatherForecast.Domain.Aggregates.WeatherForecast.Values.Wind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DirectionFirst")
                        .HasColumnType("integer");

                    b.Property<int>("DirectionSecond")
                        .HasColumnType("integer");

                    b.Property<double>("SpeedWindInMetersPerSecond")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Wind");
                });

            modelBuilder.Entity("WeatherForecast.Domain.Aggregates.Account.Account", b =>
                {
                    b.OwnsMany("WeatherForecast.Domain.Aggregates.Account.Values.Device", "Devices", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("OnlineAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AccountId", "Id");

                            b1.ToTable("Device");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("WeatherForecast.Domain.Aggregates.ForecastWeather.ForecastWeather", b =>
                {
                    b.HasOne("WeatherForecast.Domain.Aggregates.WeatherForecast.Values.Wind", "Wind")
                        .WithMany()
                        .HasForeignKey("WindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wind");
                });
#pragma warning restore 612, 618
        }
    }
}
